/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import Controladores_Yoshiro.ControladorPersonalizarComidas;

/**
 * 
 *
 * @author fresi
 */
public class Personalizar_comidas extends javax.swing.JFrame {
    ControladorPersonalizarComidas objControladorPersonalizarComidas;
    /**
     * Creates new form Personalizar_comidas
     */
    public Personalizar_comidas() {
        initComponents();
        objControladorPersonalizarComidas = new ControladorPersonalizarComidas(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox<>();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jComboBox2 = new javax.swing.JComboBox<>();
        jTextField2 = new javax.swing.JTextField();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(219, 215, 194));
        jButton1.setText("jButton1");
        jButton1.setBorder(null);

        jButton2.setBackground(new java.awt.Color(219, 215, 194));
        jButton2.setText("jButton2");
        jButton2.setBorder(null);

        jButton3.setBackground(new java.awt.Color(219, 215, 194));
        jButton3.setText("jButton3");
        jButton3.setBorder(null);

        jButton4.setBackground(new java.awt.Color(219, 215, 194));
        jButton4.setText("jButton4");
        jButton4.setBorder(null);

        jButton5.setBackground(new java.awt.Color(219, 215, 194));
        jButton5.setText("jButton5");
        jButton5.setBorder(null);

        jButton6.setBackground(new java.awt.Color(228, 208, 194));
        jButton6.setText("jButton6");
        jButton6.setBorder(null);

        jButton7.setBackground(new java.awt.Color(228, 208, 194));
        jButton7.setText("jButton7");
        jButton7.setBorder(null);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-Seleccione-" }));
        getContentPane().add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 160, 150, -1));

        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 250, 200, -1));

        jButton8.setBackground(new java.awt.Color(219, 215, 194));
        jButton8.setText("jButton1");
        jButton8.setBorder(null);
        getContentPane().add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(55, 383, 80, 30));

        jButton9.setBackground(new java.awt.Color(219, 215, 194));
        jButton9.setText("jButton2");
        jButton9.setBorder(null);
        getContentPane().add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 383, 80, 30));

        jButton10.setBackground(new java.awt.Color(219, 215, 194));
        jButton10.setText("jButton3");
        jButton10.setBorder(null);
        getContentPane().add(jButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(345, 383, 80, 30));

        jButton11.setBackground(new java.awt.Color(219, 215, 194));
        jButton11.setText("jButton4");
        jButton11.setBorder(null);
        getContentPane().add(jButton11, new org.netbeans.lib.awtextra.AbsoluteConstraints(125, 443, 80, 30));

        jButton12.setBackground(new java.awt.Color(219, 215, 194));
        jButton12.setText("jButton5");
        jButton12.setBorder(null);
        getContentPane().add(jButton12, new org.netbeans.lib.awtextra.AbsoluteConstraints(265, 443, 80, 30));

        jButton13.setBackground(new java.awt.Color(228, 208, 194));
        jButton13.setText("jButton6");
        jButton13.setBorder(null);
        getContentPane().add(jButton13, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 593, 100, 30));

        jButton14.setBackground(new java.awt.Color(228, 208, 194));
        jButton14.setText("jButton7");
        jButton14.setBorder(null);
        getContentPane().add(jButton14, new org.netbeans.lib.awtextra.AbsoluteConstraints(345, 593, 100, 30));

        jPanel1.setBackground(new java.awt.Color(236, 230, 211));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 540, 100, 20));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/personalizar plato.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Personalizar_comidas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Personalizar_comidas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Personalizar_comidas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Personalizar_comidas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Personalizar_comidas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    public javax.swing.JButton jButton10;
    public javax.swing.JButton jButton11;
    public javax.swing.JButton jButton12;
    public javax.swing.JButton jButton13;
    public javax.swing.JButton jButton14;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    public javax.swing.JButton jButton8;
    public javax.swing.JButton jButton9;
    private javax.swing.JComboBox<String> jComboBox1;
    public javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    public javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
